#! /usr/bin/env bash

set -e

RUN_COMMAND="talisker.gunicorn app:create_app() --bind $1 --name talisker-`hostname` --access-logfile -"

if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    RUN_COMMAND="${RUN_COMMAND} --reload --log-level debug --timeout 9999"
fi

${RUN_COMMAND}
